
cartesian_pose_example_controller:
    type: panda_controllers/CartesianPoseExampleController
    arm_id: panda

elbow_example_controller:
    type: panda_controllers/ElbowExampleController
    arm_id: panda

cartesian_velocity_example_controller:
    type: panda_controllers/CartesianVelocityExampleController
    arm_id: panda

force_example_controller:
    type: panda_controllers/ForceExampleController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

cartesian_impedance_example_controller:
    type: panda_controllers/CartesianImpedanceExampleController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
